dist: xenial
language: python
cache: pip
python:
  - "3.6"
env:
  - REQ=""
matrix:
  include:
    - python: "3.5"
      env: REQ="Django>=1.11,<2.0"
    - python: "3.5"
      env: REQ="Django>=2.0,<2.1"
    - python: "3.5"
      env: REQ="Django>=2.1,<2.2"
    - python: "3.5"
      env: REQ="Django>=2.2,<3.0"
    - python: "3.6"
      env: REQ="Django>=1.11,<2.0"
    - python: "3.6"
      env: REQ="Django>=2.0,<2.1"
    - python: "3.6"
      env: REQ="Django>=2.1,<2.2"
    - python: "3.6"
      env: REQ="Django>=2.2,<3.0"
    - python: "3.7"
      env: REQ="Django>=1.11,<2.0"
    - python: "3.7"
      env: REQ="Django>=2.0,<2.1"
    - python: "3.7"
      env: REQ="Django>=2.1,<2.2"
    - python: "3.7"
      env: REQ="Django>=2.2,<3.0"
install:
  - pip install -U pip setuptools coverage coveralls
  - pip install $REQ
script: "coverage run --source csvexport/ tests/manage.py test testapp"
after_success:
  - coverage report
  - coveralls
